export const GETRECRUITER_REQUEST = 'GetRecruiterReducer/GETRECRUITER_REQUEST';
export const GETRECRUITER_SUCCESS = 'GetRecruiterReducer/GETRECRUITER_SUCCESS';
export const GETRECRUITER_FAILED = 'GetRecruiterReducer/GETRECRUITER_FAILED';
